AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
Metrics/LineLength:
  Max: 120
Layout/DotPosition:
  EnforcedStyle: trailing
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
# TODO: re-enable
Style/Documentation:
  Enabled: false
