name: CI

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        ruby: [ '2.6', '2.7', '3.0' ]
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
        with:
          ruby-version: ${{ matrix.ruby }}
          cache-key: gems-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('Gemfile', 'antex.gemspec') }}
          cache-restore-keys: gems-${{ matrix.os }}-${{ matrix.ruby }}-

      - name: Setup TeX Live
        uses: paolobrasolin/setup-texlive-action@main
        with:
          cache-key: texlive-${{ matrix.os }}
          packages-path: ${{ github.workspace }}/.github/texlive.packages
          profile-path: ${{ github.workspace }}/.github/texlive.profile

      - name: Run tests
        run: bundle exec rspec

